apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    service: {{ .Release.Name }}-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-mongodb
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: {{ .Release.Name }}
      {{ end }}
      containers:
      - name: {{ .Release.Name }}-mongodb
        image: {{ .Values.image.repo }}/{{ .Values.image.prefix }}-mongodb:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
