apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    service: {{ .Release.Name }}-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
  selector:
    service: {{ .Release.Name }}-mongodb
