apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    service: {{ .Release.Name }}-redis
spec:
  ports:
  - name: redis
    port: 6379
  selector:
    service: {{ .Release.Name }}-redis
