{{- if  .Capabilities.APIVersions.Has "monitoring.coreos.com/v1"  }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
spec:
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
  jobLabel: otel-shop
  selector:
    matchLabels:
      app.kubernetes.io/name: "otel-shop"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}