apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-shipping
  labels:
    service: {{ .Release.Name }}-shipping
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: {{ .Release.Name }}-shipping
