apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-shipping
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  labels:
    app.kubernetes.io/name: "otel-shop"
    service: {{ .Release.Name }}-shipping
spec:
  ports:
  - name: http
    port: 8080
  selector:
    service: {{ .Release.Name }}-shipping
