apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    service: {{ .Release.Name }}-web
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: {{ .Release.Name }}-web
  {{ if .Values.nodeport }}
  type: NodePort
  {{ else }}
  type: LoadBalancer
  {{ end }}
---
{{if .Values.ocCreateRoute}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-web
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-web
{{end}}
