apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}-catalogue
  name: {{ .Release.Name }}-catalogue
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: {{ .Release.Name }}-catalogue
