apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    service: {{ .Release.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-mysql
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: {{ .Release.Name }}-mysql
        image: {{ .Values.image.repo }}/{{ .Values.image.prefix }}-mysql-db:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # added for Istio
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 700Mi
      restartPolicy: Always
