apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ratings
  labels:
    service: {{ .Release.Name }}-ratings
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: {{ .Release.Name }}-ratings
