name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    name: Bump version
    outputs:
      bumped_sha: ${{ steps.sha.outputs.SHA }}
      new_version: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2

      - name: Bump version
        uses: remorses/bump-version@js
        with:
          version_file: ./VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'

      - name: Get Version
        id: version
        run: |
          echo ::set-output name=VERSION::$(cat ./VERSION)
        if: github.ref == 'refs/heads/master'

      - name: Push changes to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
        if: github.ref == 'refs/heads/master'
      - name: get sha
        id: sha
        run: |
          sha_new=$(git rev-parse HEAD)
          echo $sha_new
          echo "::set-output name=SHA::$sha_new"
        if: github.ref == 'refs/heads/master'
      - run:
          echo ${{ steps.sha.outputs.SHA }}
        if: github.ref == 'refs/heads/master'

  build:
    needs: bump
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - mongodb
          - redis
          - rabbitmq
          - mysql
          - dispatch
          - front
          - web
          - cart
          - catalogue
          - user
          - payment
          - shipping
          - ratings
          - load
    env:
        SERVICE: ${{matrix.service}}
        DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.bump.outputs.SHA }}
          fetch-depth: 0
        if: github.ref == 'refs/heads/master'
      - uses: actions/checkout@v2
        if: github.ref != 'refs/heads/master'

      - run: cp .env.template .env
        shell: bash

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'

      - name: Pull service ${{matrix.service}}
        run: docker-compose -f docker-compose.yaml -f docker-compose-load.yaml pull --ignore-pull-failures ${{matrix.service}}

      - name: Build service ${{matrix.service}}
        run: docker-compose -f docker-compose.yaml -f docker-compose-load.yaml build ${{matrix.service}}

      - name: Push service ${{matrix.service}}
        run: docker-compose -f docker-compose.yaml -f docker-compose-load.yaml push ${{matrix.service}}
        if: github.ref == 'refs/heads/master'

  tag_release:
    needs:
      - bump
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.bump.outputs.SHA }}
          fetch-depth: 0
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ needs.bump.outputs.new_version }}
          message: '${{ needs.bump.outputs.new_version }}: Automatic release'
    if: github.ref == 'refs/heads/master'

  chart_release:
    needs: tag_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: K8s/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: github.ref == 'refs/heads/master'
