name: Release
on:
  release:
    types: [published, prereleased, released]

jobs:
  release_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: K8s/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  release_asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Package Helm Chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package K8s/charts/otel-shop
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} otel-shop-${{ github.event.release.tag_name }}.tgz
